name: chatbox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  get: ^4.7.3
  get_it: ^9.1.1
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^5.4.4
  flutter_launcher_icons: ^0.14.4
  google_nav_bar: ^5.0.7
  firebase_messaging: ^16.0.4
  emoji_picker_flutter: ^4.4.0
  image_picker: ^1.2.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  video_player: ^2.10.0
  firebase_storage: ^13.0.4
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon1.png"  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
